"""Deterministic P01-compatible fixtures (ADR-0007, spec §2.1, §6).

**These are synthetic fixtures, not real market data and not P01 output.**

They exist so that P02 can be developed and tested without the real P01
deployment, exactly as ADR-0007 requires. Every descriptor produced here sets
``is_fixture=True`` and carries an explicit limitation string, so no downstream
artifact, report, or metric can be mistaken for a market-data result.

Determinism strategy
--------------------
Prices are generated as **integer ticks** via a linear congruential generator
with pure integer arithmetic, then divided by ``100.0`` once. No transcendental
functions, no ``random`` module, no platform-dependent math. The byte output of
this module is therefore identical across platforms, Python patch versions, and
CPU architectures — which is what byte-level reproducibility checks need.
"""

from __future__ import annotations

from collections.abc import Iterable
from datetime import UTC, datetime, timedelta

from pydantic import BaseModel, Field

from qrsip.data.contract import Bar, DatasetDescriptor, DatasetHandle
from qrsip.errors import QRSIPError
from qrsip.infrastructure.storage import canonical_json_bytes, sha256_hex

__all__ = [
    "DEFAULT_FIXTURE",
    "FIXTURE_LIMITATION",
    "FIXTURE_SOURCE_VERSION",
    "FixtureP01Provider",
    "FixtureSpec",
    "build_fixture_bars",
]

FIXTURE_SOURCE_VERSION = "1.0.0"

FIXTURE_LIMITATION = (
    "SYNTHETIC FIXTURE: generated by qrsip.data.fixtures from a deterministic "
    "pseudo-random walk. This is NOT real market data and NOT P01 production "
    "output. Results computed from it demonstrate platform mechanics only and "
    "carry no market evidence."
)

_MODULUS = 1 << 64
_MULTIPLIER = 6364136223846793005
_INCREMENT = 1442695040888963407


class _Ticks:
    """Deterministic 64-bit LCG returning unsigned integers.

    Integer-only arithmetic guarantees identical output on every platform.
    """

    __slots__ = ("_state",)

    def __init__(self, seed: int) -> None:
        if not isinstance(seed, int) or isinstance(seed, bool):
            raise QRSIPError("fixture seed must be an integer", seed=repr(seed))
        self._state = seed % _MODULUS

    def next_uint(self) -> int:
        self._state = (self._state * _MULTIPLIER + _INCREMENT) % _MODULUS
        return self._state >> 33  # 31 significant bits keeps all math exact

    def bounded(self, low: int, high: int) -> int:
        """Return an integer uniform in ``[low, high]`` (inclusive)."""
        if high < low:
            raise QRSIPError("invalid bounded range", low=low, high=high)
        return low + (self.next_uint() % (high - low + 1))


def build_fixture_bars(
    instrument: str,
    *,
    start: datetime,
    periods: int,
    seed: int,
    start_price: float = 100.0,
    max_move_ticks: int = 150,
    base_volume: int = 1_000_000,
    bar_interval: timedelta = timedelta(days=1),
) -> tuple[Bar, ...]:
    """Build a deterministic synthetic OHLCV series for one instrument.

    The generated series is a bounded random walk on integer cents. OHLC
    relationships hold exactly by construction, volume is strictly positive, and
    the same arguments always produce byte-identical bars.
    """
    if not instrument or not instrument.strip():
        raise QRSIPError("fixture instrument must be a non-empty string")
    if periods <= 0:
        raise QRSIPError("fixture periods must be positive", periods=periods)
    if start.tzinfo is None or start.utcoffset() is None:
        raise QRSIPError("fixture start must be timezone-aware", start=str(start))
    if start_price <= 0:
        raise QRSIPError("fixture start_price must be positive", start_price=start_price)
    if max_move_ticks <= 0:
        raise QRSIPError("fixture max_move_ticks must be positive", max_move_ticks=max_move_ticks)

    rng = _Ticks(seed)
    price_ticks = round(start_price * 100.0)
    bars: list[Bar] = []

    for index in range(periods):
        timestamp = start + bar_interval * index
        open_ticks = price_ticks
        close_ticks = max(100, open_ticks + rng.bounded(-max_move_ticks, max_move_ticks))
        span = rng.bounded(0, max_move_ticks)
        high_ticks = max(open_ticks, close_ticks) + span
        low_ticks = max(1, min(open_ticks, close_ticks) - span)
        volume = base_volume + rng.bounded(0, base_volume // 2)

        bars.append(
            Bar(
                timestamp=timestamp,
                instrument=instrument.strip(),
                open=open_ticks / 100.0,
                high=high_ticks / 100.0,
                low=low_ticks / 100.0,
                close=close_ticks / 100.0,
                volume=float(volume),
            )
        )
        price_ticks = close_ticks

    return tuple(bars)


def _bars_checksum(bars: tuple[Bar, ...]) -> str:
    """Content identity for a fixture series (canonical bytes -> SHA-256)."""
    rows = [
        [
            bar.timestamp.isoformat(),
            bar.instrument,
            repr(bar.open),
            repr(bar.high),
            repr(bar.low),
            repr(bar.close),
            repr(bar.volume),
        ]
        for bar in bars
    ]
    return sha256_hex(canonical_json_bytes(rows))


class FixtureSpec(BaseModel):
    """Declarative description of one deterministic fixture dataset."""

    model_config = {"frozen": True, "extra": "forbid"}

    dataset_id: str = Field(..., min_length=1)
    version: str = Field(default="1.0.0", min_length=1)
    instruments: tuple[str, ...] = Field(default=("FIXTURE-EQ",))
    periods: int = Field(default=504, ge=1)
    start: datetime = Field(default_factory=lambda: datetime(2020, 1, 1, tzinfo=UTC))
    seed: int = Field(default=42)
    start_price: float = Field(default=100.0, gt=0.0)
    base_volume: int = Field(default=1_000_000, gt=0)
    bar_interval_days: int = Field(default=1, ge=1)


DEFAULT_FIXTURE = FixtureSpec(dataset_id="FIXTURE-P01-EQUITY-DAILY")


class FixtureP01Provider:
    """Deterministic P01-compatible provider backed by synthetic fixtures.

    Implements :class:`~qrsip.data.contract.P01DataContract`. Every descriptor
    it returns carries ``is_fixture=True`` plus :data:`FIXTURE_LIMITATION`, so
    downstream artifacts cannot present fixture output as market evidence.
    """

    def __init__(self, specs: Iterable[FixtureSpec] = (DEFAULT_FIXTURE,)) -> None:
        resolved = tuple(specs)
        if not resolved:
            raise QRSIPError("FixtureP01Provider requires at least one FixtureSpec")
        self._specs: dict[tuple[str, str], FixtureSpec] = {}
        for spec in resolved:
            if not spec.instruments:
                raise QRSIPError(
                    "fixture spec requires at least one instrument",
                    dataset_id=spec.dataset_id,
                )
            key = (spec.dataset_id, spec.version)
            if key in self._specs:
                raise QRSIPError(
                    "duplicate fixture spec",
                    dataset_id=spec.dataset_id,
                    version=spec.version,
                )
            self._specs[key] = spec

    # -- P01DataContract --------------------------------------------------
    def list_datasets(self) -> list[DatasetDescriptor]:
        """Return descriptors sorted by ``(dataset_id, version)``."""
        return [self.describe(*key) for key in sorted(self._specs)]

    def describe(self, dataset_id: str, version: str) -> DatasetDescriptor:
        """Return the descriptor for ``(dataset_id, version)``; fail closed."""
        spec = self._require(dataset_id, version)
        bars = self._bars(spec)
        return DatasetDescriptor(
            dataset_id=spec.dataset_id,
            version=spec.version,
            source="qrsip.data.fixtures.FixtureP01Provider",
            source_version=FIXTURE_SOURCE_VERSION,
            instruments=spec.instruments,
            frequency=f"{spec.bar_interval_days}d",
            timezone="UTC",
            schema_version="1.0.0",
            coverage_start=bars[0].timestamp,
            coverage_end=bars[-1].timestamp,
            is_fixture=True,
            limitations=(FIXTURE_LIMITATION,),
        )

    def load(self, dataset_id: str, version: str) -> tuple[DatasetHandle, tuple[Bar, ...]]:
        """Return the handle and bars ordered by ``(timestamp, instrument)``."""
        spec = self._require(dataset_id, version)
        bars = self._bars(spec)
        handle = DatasetHandle(
            descriptor=self.describe(dataset_id, version),
            checksum=_bars_checksum(bars),
            row_count=len(bars),
        )
        return handle, bars

    # -- internals --------------------------------------------------------
    def _require(self, dataset_id: str, version: str) -> FixtureSpec:
        try:
            return self._specs[(dataset_id, version)]
        except KeyError as exc:
            raise QRSIPError(
                "unknown fixture dataset",
                dataset_id=dataset_id,
                version=version,
                known=[f"{d}@{v}" for d, v in sorted(self._specs)],
            ) from exc

    def _bars(self, spec: FixtureSpec) -> tuple[Bar, ...]:
        """Build this spec's bars, ordered by ``(timestamp, instrument)``."""
        collected: list[Bar] = []
        for instrument in spec.instruments:
            collected.extend(
                build_fixture_bars(
                    instrument,
                    start=spec.start,
                    periods=spec.periods,
                    seed=spec.seed,
                    start_price=spec.start_price,
                    base_volume=spec.base_volume,
                    bar_interval=timedelta(days=spec.bar_interval_days),
                )
            )
        return tuple(sorted(collected, key=lambda bar: (bar.timestamp, bar.instrument)))
